import { simpleGit, type SimpleGit } from 'simple-git';
import { mkdirSync, writeFileSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import type { Chapter, Decision, Requirement } from '../db/types';
import { stripChapterHeading } from '../markdown';
import { effectiveStatus, pendingByChapter } from '../llm/decisions';
import { createLocks } from '../llm/lock';
import { chapterPath } from '../llm/subchapters';
import type { ExportInput } from '../llm/export';
import { validateDocument } from '../llm/validation';

/**
 * One Git repository per application.
 *
 * Working repositories (not bare) under `data/repos/<slug>`, so chapters can be
 * written as files and diffed as prose. `RemoteHost` in `host.ts` is the seam
 * for pushing to GitHub and opening real pull requests later.
 */

export const MAIN_BRANCH = 'main';

export function repoPathFor(slug: string): string {
	return resolve(process.cwd(), 'data', 'repos', slug);
}

function git(repoPath: string): SimpleGit {
	return simpleGit(repoPath);
}

const locks = createLocks();

/**
 * Hold this repository for the whole of `work`.
 *
 * Everything that *writes* runs inside one of these, and checkout, write and
 * commit go in together — holding them one git call at a time would order the
 * calls while still letting two turns interleave between them, which is the
 * problem rather than the fix.
 *
 * Reads are deliberately outside. `diffAgainstMain`, `log` and `manifestOnMain`
 * read committed history rather than the working tree, so they are consistent
 * whatever a writer is doing, and putting page loads behind the write queue
 * would make reading an application wait on someone else's conversation.
 */
export function withRepo<T>(repoPath: string, work: () => Promise<T>): Promise<T> {
	return locks.run(repoPath, work);
}

/**
 * The repository was not on the branch the caller meant to write to.
 *
 * Its own type because the caller has to tell it apart: this is the failure that
 * would otherwise have put a change on `main` without anyone approving it.
 */
export class WrongBranch extends Error {
	// Written out rather than declared as constructor parameter properties: Node's
	// type stripping rejects those, and `scripts/test-repo.mjs` loads this module
	// directly. Anything the tests reach has to survive being stripped, not
	// compiled.
	readonly repoPath: string;
	readonly expected: string;
	readonly actual: string;

	constructor(repoPath: string, expected: string, actual: string) {
		super(`Expected ${repoPath} to be on "${expected}" but it is on "${actual}" — refusing to commit`);
		this.name = 'WrongBranch';
		this.repoPath = repoPath;
		this.expected = expected;
		this.actual = actual;
	}
}

/**
 * Filename for a chapter: `docs/070-security.md`, and `docs/020-01-booking.md`
 * for a sub-chapter. Flat directory, but the names sort into reading order.
 *
 * A sub-chapter needs its parent's position, so the whole set is resolved
 * together by `chapterFilenames`.
 */
export function chapterFilename(
	chapter: Pick<Chapter, 'key' | 'position'> & { parent_key?: string },
	parentPosition = 0
): string {
	return chapterPath(
		{ key: chapter.key, parent_key: chapter.parent_key ?? '', position: chapter.position },
		parentPosition
	);
}

/** Every chapter's file name, resolving sub-chapters against their parent. */
export function chapterFilenames(chapters: Chapter[]): Map<string, string> {
	const positionOf = new Map(chapters.map((c) => [c.key, c.position]));
	return new Map(
		chapters.map((c) => [c.key, chapterFilename(c, positionOf.get(c.parent_key) ?? 0)])
	);
}

export async function ensureRepo(repoPath: string, projectName: string): Promise<void> {
	if (existsSync(join(repoPath, '.git'))) return;

	mkdirSync(join(repoPath, 'docs'), { recursive: true });

	const g = git(repoPath);
	await g.init(['--initial-branch', MAIN_BRANCH]);
	await g.addConfig('user.name', 'Specman');
	await g.addConfig('user.email', 'specman@localhost');

	writeFileSync(
		join(repoPath, 'README.md'),
		`# ${projectName}\n\nDesign document generated by Specman.\n`,
		'utf8'
	);
	writeFileSync(join(repoPath, '.gitignore'), 'node_modules/\n', 'utf8');

	await g.add('.');
	await g.commit('Initialise design document');
}

const SCOPE_HEADING: Record<string, string> = {
	now: 'Must be true',
	later: 'Agreed, but not in the first version',
	out: 'Deliberately not doing'
};

/**
 * Requirements as Markdown, grouped by scope.
 *
 * `WHEN`/`THEN` are kept in the file even though the UI hides them: the file is
 * what a developer or a coding agent reads, and the markers are what make a
 * requirement testable rather than decorative.
 */
function renderRequirements(requirements: Pick<ExportInput['requirements'][number], 'ref' | 'scope' | 'statement' | 'scenarios'>[]): string {
	if (requirements.length === 0) return '';

	const sections: string[] = [];

	for (const scope of ['now', 'later', 'out'] as const) {
		const group = requirements.filter((r) => r.scope === scope);
		if (group.length === 0) continue;

		sections.push(`### ${SCOPE_HEADING[scope]}`, '');

		for (const req of group) {
			sections.push(`#### ${req.ref}`, '', req.statement, '');
			for (const scenario of req.scenarios) {
				sections.push(`- **WHEN** ${scenario.when}`, `  **THEN** ${scenario.then}`);
			}
			if (req.scenarios.length > 0) sections.push('');
		}
	}

	// Blank line first: the body above ends without one, and a heading run up
	// against the previous paragraph reads as part of it in a plain-text diff.
	return `\n\n## Requirements\n\n${sections.join('\n')}`;
}

/** Writes chapter files, the manifest, and the assembled README. Does not commit. */
export function writeDocument(
	repoPath: string,
	projectName: string,
	chapters: Chapter[],
	requirements: Requirement[] = [],
	decisions: Decision[] = []
): void {
	mkdirSync(join(repoPath, 'docs'), { recursive: true });

	const fileOf = chapterFilenames(chapters);

	// Remove stale chapter files so a renamed or deleted chapter doesn't linger.
	const expected = new Set(fileOf.values());
	const docsDir = join(repoPath, 'docs');
	if (existsSync(docsDir)) {
		for (const entry of readdirSync(docsDir)) {
			if (!expected.has(`docs/${entry}`)) rmSync(join(docsDir, entry), { force: true });
		}
	}

	// A chapter resting on unconfirmed assumptions is not finished, so the files
	// must not claim it is either. Same derivation the UI uses.
	const pending = pendingByChapter(decisions);
	const statusOf = (chapter: Chapter) => effectiveStatus(chapter.status, pending.get(chapter.key) ?? 0);

	const byChapter = new Map<string, Requirement[]>();
	for (const req of requirements) {
		const list = byChapter.get(req.chapter_key) ?? [];
		list.push(req);
		byChapter.set(req.chapter_key, list);
	}

	// A chapter that has been split holds its content in its sections, and calling
	// that unwritten would be wrong in the one file where it is most likely to be
	// read on its own.
	const sectionsOf = new Map<string, Chapter[]>();
	for (const chapter of chapters) {
		if (!chapter.parent_key) continue;
		const list = sectionsOf.get(chapter.parent_key) ?? [];
		list.push(chapter);
		sectionsOf.set(chapter.parent_key, list);
	}

	for (const chapter of chapters) {
		const content = stripChapterHeading(chapter.content_md ?? '', chapter.title);
		const sections = sectionsOf.get(chapter.key) ?? [];
		// A chapter set aside says why, so the judgement is on the record rather
		// than looking like an omission.
		const body =
			chapter.applicable === 0
				? `_Not needed for this application. ${chapter.skip_reason}_`
				: content ||
					(sections.length > 0
						? `_Written as ${sections.length} parts:_\n\n${sections
								.map((s) => `- [${s.title}](${(fileOf.get(s.key) ?? '').replace('docs/', '')})`)
								.join('\n')}`
						: '_This chapter has not been written yet._');
		const goal = chapter.goal ? `_${chapter.goal}_\n\n` : '';

		const openQuestions = chapter.open_questions.length
			? `\n\n### Open questions\n\n${chapter.open_questions.map((q) => `- ${q}`).join('\n')}\n`
			: '\n';

		writeFileSync(
			join(repoPath, fileOf.get(chapter.key)!),
			`# ${chapter.title}\n\n${goal}${body}${renderRequirements(byChapter.get(chapter.key) ?? [])}${openQuestions}`,
			'utf8'
		);
	}

	const manifest = {
		project: projectName,
		generated_by: 'specman',
		chapters: chapters.map((c) => ({
			key: c.key,
			title: c.title,
			goal: c.goal ?? '',
			parent: c.parent_key ?? '',
			file: fileOf.get(c.key)!,
			status: statusOf(c),
			open_questions: c.open_questions
		})),
		// Mirrored here so a change can be reviewed as a requirement-level delta
		// rather than a text diff, and so the repository stays self-describing.
		requirements: requirements.map((r) => ({
			ref: r.ref,
			chapter: r.chapter_key,
			scope: r.scope,
			statement: r.statement,
			scenarios: r.scenarios
		})),
		decisions: decisions.map((d) => ({
			chapter: d.chapter_key,
			statement: d.statement,
			rationale: d.rationale,
			decided_by: d.source,
			status: d.status
		}))
	};
	writeFileSync(
		join(repoPath, 'specman.manifest.json'),
		JSON.stringify(manifest, null, 2) + '\n',
		'utf8'
	);

	const inScope = chapters.filter((c) => c.applicable !== 0);
	const complete = inScope.filter((c) => statusOf(c) === 'complete').length;
	const readme = [
		`# ${projectName}`,
		'',
		`Design document generated by Specman — ${complete} of ${inScope.length} chapters complete.`,
		'',
		'## Contents',
		'',
		...chapters.map((c) => {
			const open = c.open_questions.length ? ` (${c.open_questions.length} open)` : '';
			const indent = c.parent_key ? '  ' : '';
			return `${indent}- [${c.title}](${fileOf.get(c.key)}) — ${statusOf(c).replace('_', ' ')}${open}`;
		}),
		'',
		'---',
		'',
		...chapters.flatMap((c) => [
			`${c.parent_key ? '###' : '##'} ${c.title}`,
			'',
			stripChapterHeading(c.content_md ?? '', c.title) || '_Not written yet._',
			renderRequirements(byChapter.get(c.key) ?? []),
			''
		])
	].join('\n');

	writeFileSync(join(repoPath, 'README.md'), readme, 'utf8');

	writeDecisionLog(repoPath, chapters, decisions);
}

const DECIDED_BY: Record<string, string> = {
	user: 'Decided by the requester',
	agent: 'Chosen by the assistant',
	standard: 'Inherited from a company standard'
};

/**
 * `decisions.md` — what was settled, and by whom.
 *
 * Written even when empty so the file exists in every repository and its absence
 * never has to be interpreted. Anything the assistant chose is marked, and
 * marked again if it has not been confirmed, because that is exactly what a
 * reviewer needs to look at hardest.
 */
function writeDecisionLog(repoPath: string, chapters: Chapter[], decisions: Decision[]): void {
	const lines: string[] = ['# Decisions', ''];

	if (decisions.length === 0) {
		lines.push('_Nothing has been decided yet._');
	} else {
		const pending = decisions.filter((d) => d.source !== 'user' && d.status !== 'confirmed').length;
		lines.push(
			pending > 0
				? `${decisions.length} decisions recorded. **${pending} were made by the assistant and are still unconfirmed.**`
				: `${decisions.length} decisions recorded, all confirmed.`,
			''
		);

		for (const chapter of chapters) {
			const own = decisions.filter((d) => d.chapter_key === chapter.key);
			if (own.length === 0) continue;

			lines.push(`## ${chapter.title}`, '');
			for (const decision of own) {
				const unconfirmed = decision.source !== 'user' && decision.status !== 'confirmed';
				lines.push(
					`- **${decision.statement}**`,
					`  ${DECIDED_BY[decision.source] ?? decision.source}${unconfirmed ? ' — not yet confirmed' : ''}`
				);
				if (decision.rationale) lines.push(`  Why: ${decision.rationale}`);
			}
			lines.push('');
		}
	}

	writeFileSync(join(repoPath, 'decisions.md'), lines.join('\n') + '\n', 'utf8');
}

/**
 * The manifest as it stands on `main` — the approved document.
 *
 * Returns null when there is nothing to compare against: a repository whose
 * first proposal has not been merged yet has no manifest on main at all, and
 * that is a normal state, not a failure.
 */
export async function manifestOnMain(repoPath: string): Promise<Record<string, any> | null> {
	return manifestOnBranch(repoPath, MAIN_BRANCH);
}

export async function manifestOnBranch(repoPath: string, branch: string): Promise<Record<string, any> | null> {
	try {
		const raw = await git(repoPath).show([`${branch}:specman.manifest.json`]);
		return JSON.parse(raw);
	} catch {
		return null;
	}
}

/** Read a single committed revision, including proposals written before snapshots existed. */
export async function specInputOnBranch(repoPath: string, branch: string): Promise<ExportInput> {
	const g = git(repoPath);
	const revision = (await g.revparse([branch])).trim();
	const files = (await g.raw(['ls-tree', '-r', '--name-only', revision])).split('\n');
	if (files.includes('specman.export.json')) {
		return JSON.parse(await g.show([`${revision}:specman.export.json`])) as ExportInput;
	}

	// Older manifests did not record every export field. Preserve their committed
	// prose and rules, and flag the missing metadata rather than consulting SQLite.
	const manifest = JSON.parse(await g.show([`${revision}:specman.manifest.json`]));
	const requirements: ExportInput['requirements'] = (manifest.requirements ?? []).map((r: Record<string, any>) => ({
		ref: r.ref, chapter_key: r.chapter, statement: r.statement, scope: r.scope,
		scenarios: r.scenarios ?? [], source: r.source ?? 'agent', existing: r.existing ?? 0
	}));
	const decisions: ExportInput['decisions'] = (manifest.decisions ?? []).map((d: Record<string, any>) => ({
		chapter_key: d.chapter, statement: d.statement, rationale: d.rationale ?? '',
		source: d.decided_by, status: d.status
	}));
	const chapters: ExportInput['chapters'] = await Promise.all(manifest.chapters.map(async (c: Record<string, any>, position: number) => {
		let prose = stripChapterHeading(await g.show([`${revision}:${c.file}`]), c.title).trim();
		const questions: string[] = c.open_questions ?? [];
		const questionTail = questions.length ? `### Open questions\n\n${questions.map((q) => `- ${q}`).join('\n')}` : '';
		if (questionTail && prose.endsWith(questionTail)) prose = prose.slice(0, -questionTail.length).trimEnd();
		const rules = renderRequirements(requirements.filter((r) => r.chapter_key === c.key)).trim();
		if (rules && prose.endsWith(rules)) prose = prose.slice(0, -rules.length).trimEnd();
		const goal = c.goal ? `_${c.goal}_` : '';
		if (goal && prose.startsWith(goal)) prose = prose.slice(goal.length).trimStart();
		const skipped = /^_Not needed for this application\. (.*)_$/s.exec(prose);
		if (prose === '_This chapter has not been written yet._' || /^_Written as \d+ parts:_\n/.test(prose)) prose = '';
		const prefix = c.parent ? /^docs\/\d+-(\d+)-/.exec(c.file) : /^docs\/(\d+)-/.exec(c.file);
		const recordedPosition = prefix ? (c.parent ? Number(prefix[1]) - 1 : Number(prefix[1]) / 10) : position;
		return {
			key: c.key, title: c.title, goal: c.goal ?? '', status: c.status,
			content_md: skipped ? '' : prose, position: recordedPosition, parent_key: c.parent ?? '',
			applicable: skipped ? 0 : 1, skip_reason: skipped?.[1] ?? '', open_questions: questions
		};
	}));
	return {
		project: { name: manifest.project, description: '', kind: 'new' },
		chapters, requirements, decisions,
		problems: [
			...validateDocument({ chapters: chapters.filter((c) => c.applicable !== 0), requirements, decisions }),
			{ severity: 'warning', message: 'This older proposal did not record the application description, application type, or which requirements describe existing behaviour. Confirm those with the requester before building.' }
		]
	};
}

/**
 * Writes the build-ready bundle under `spec/`.
 *
 * The directory is rebuilt rather than merged, so a chapter that was renamed or
 * set aside cannot leave a stale file behind for someone to build from.
 */
export function writeSpecBundle(repoPath: string, files: Map<string, string>): void {
	const root = join(repoPath, 'spec');
	rmSync(root, { recursive: true, force: true });

	for (const [relative, contents] of files) {
		const target = join(root, relative);
		mkdirSync(dirname(target), { recursive: true });
		writeFileSync(target, contents.endsWith('\n') ? contents : `${contents}\n`, 'utf8');
	}
}

export async function hasChanges(repoPath: string): Promise<boolean> {
	const status = await git(repoPath).status();
	return !status.isClean();
}

/**
 * Stage everything and commit — on `expectedBranch`, or not at all.
 *
 * The branch is checked before the working tree is, so "nothing to commit" and
 * "this is not the branch you think" cannot look the same to the caller. Getting
 * that the wrong way round would report success for a write that silently went
 * nowhere.
 */
export async function commitAll(
	repoPath: string,
	message: string,
	expectedBranch: string
): Promise<string | null> {
	const on = await currentBranch(repoPath);
	if (on !== expectedBranch) throw new WrongBranch(repoPath, expectedBranch, on);

	const g = git(repoPath);
	if (!(await hasChanges(repoPath))) return null;
	await g.add('.');
	// Git can normalize rewritten line endings back to the existing index.
	// Only the staged diff determines whether a commit actually exists.
	if (!(await g.diff(['--cached', '--name-only'])).trim()) return null;
	const result = await g.commit(message);
	return result.commit || null;
}

export async function currentBranch(repoPath: string): Promise<string> {
	return (await git(repoPath).revparse(['--abbrev-ref', 'HEAD'])).trim();
}

export async function checkoutBranch(repoPath: string, branch: string): Promise<void> {
	const g = git(repoPath);
	const branches = await g.branchLocal();
	if (branches.all.includes(branch)) {
		await g.checkout(branch);
	} else {
		await g.checkoutLocalBranch(branch);
	}
}

/**
 * Unified diff of a proposal branch against main, for the review pane.
 *
 * Scoped to what a person reads. `decisions.md` is in that set: a turn can settle
 * an assumption and change nothing else, and leaving it out made such a turn
 * produce commits while the page said there was nothing to review.
 *
 * `specman.manifest.json` and `spec/` stay out. They restate the same facts for
 * machines, and a reviewer reading their diff would be reading everything twice.
 */
export async function resolveRevision(repoPath: string, ref: string): Promise<string> {
	return (await git(repoPath).revparse(['--verify', `${ref}^{commit}`])).trim();
}

export async function revisionIsAncestor(repoPath: string, ancestor: string, descendant: string): Promise<boolean> {
	return (await git(repoPath).raw(['rev-list', '--count', `${descendant}..${ancestor}`])).trim() === '0';
}

/** Recovery can replace its generated bundle, but must not sweep other files in. */
export async function recoveryTreeSafe(repoPath: string, allowBundle: boolean): Promise<boolean> {
	// Porcelain status can be clean while Git still has an unfinished merge.
	if (['MERGE_HEAD', 'index.lock'].some((name) => existsSync(join(repoPath, '.git', name)))) return false;
	const status = await git(repoPath).status();
	if (status.isClean()) return true;
	return allowBundle && await currentBranch(repoPath) === MAIN_BRANCH &&
		status.files.every((file) => file.path.startsWith('spec/')) &&
		status.renamed.every((file) => file.from.startsWith('spec/') && file.to.startsWith('spec/'));
}

export async function onlyBundleChanged(repoPath: string, from: string, to: string): Promise<boolean> {
	const paths = (await git(repoPath).diff(['--name-only', from, to])).trim();
	return !paths || paths.split('\n').every((path) => path.startsWith('spec/'));
}

export async function diffAgainstMain(repoPath: string, branch: string, base = MAIN_BRANCH): Promise<string> {
	return git(repoPath).diff([
		`${base}...${branch}`,
		'--',
		'docs/',
		'README.md',
		'decisions.md'
	]);
}

export async function mergeToMain(repoPath: string, branch: string): Promise<void> {
	const g = git(repoPath);
	await g.checkout(MAIN_BRANCH);
	await g.merge(['--no-ff', branch, '-m', `Merge design changes from ${branch}`]);
}

export async function log(repoPath: string, limit = 20) {
	const entries = await git(repoPath).log({ maxCount: limit });
	return entries.all.map((e) => ({ hash: e.hash.slice(0, 8), date: e.date, message: e.message }));
}
